pip install pandas
pip install xlsxwriter
pip install xlrd
pip install openpyxl
pip install tkcalendar
pip install cryptography
pip install pillow
pip install requests
pip install opencv-python
pip install face_recognition
pip install imutils
pip install numpy
pip install pandas
